# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftDemo
  
  # 图片浏览器 当前版本 3.1.1
  pod 'JXPhotoBrowser'
  # 代码格式控制 '~> 0.39.2'
  pod 'SwiftLint'
  # , '~> 5.1.1'
  pod 'RxSwift'
  # , '~> 5.1.1'
  pod 'RxCocoa'
  # RxSwift 的拓展 , '~> 4.0.1'
  pod 'RxDataSources'
  # 大家都在用?
  pod 'MJRefresh'

end
